################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc_ex.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_can.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cec.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_crc.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dac.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dac_ex.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_eth.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_hcd.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2c.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2s.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_irda.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_iwdg.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_mmc.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_msp_template.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_nand.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_nor.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pccard.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd_ex.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc_ex.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_sd.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_smartcard.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi_ex.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_sram.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_timebase_rtc_alarm_template.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_timebase_tim_template.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_usart.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_wwdg.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_adc.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_crc.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_dac.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_dma.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_exti.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_fsmc.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_gpio.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_i2c.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_pwr.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_rcc.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_rtc.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_sdmmc.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_spi.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_tim.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usart.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c \
../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_utils.c 

C_DEPS += \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc_ex.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_can.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cec.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_crc.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dac.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dac_ex.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_eth.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_hcd.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2c.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2s.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_irda.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_iwdg.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_mmc.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_msp_template.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_nand.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_nor.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pccard.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd_ex.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc_ex.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_sd.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_smartcard.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi_ex.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_sram.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_timebase_rtc_alarm_template.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_timebase_tim_template.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_usart.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_wwdg.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_adc.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_crc.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_dac.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_dma.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_exti.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_fsmc.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_gpio.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_i2c.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_pwr.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_rcc.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_rtc.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_sdmmc.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_spi.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_tim.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usart.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.d \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_utils.d 

OBJS += \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc_ex.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_can.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cec.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_crc.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dac.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dac_ex.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_eth.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_hcd.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2c.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2s.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_irda.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_iwdg.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_mmc.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_msp_template.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_nand.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_nor.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pccard.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd_ex.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc_ex.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_sd.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_smartcard.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi_ex.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_sram.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_timebase_rtc_alarm_template.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_timebase_tim_template.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_usart.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_wwdg.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_adc.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_crc.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_dac.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_dma.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_exti.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_fsmc.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_gpio.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_i2c.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_pwr.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_rcc.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_rtc.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_sdmmc.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_spi.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_tim.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usart.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.obj \
./Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_utils.obj 

OBJS__QUOTED += \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_adc.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_adc_ex.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_can.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_cec.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_cortex.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_crc.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_dac.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_dac_ex.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_dma.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_eth.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_flash.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_flash_ex.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_gpio.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_gpio_ex.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_hcd.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_i2c.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_i2s.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_irda.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_iwdg.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_mmc.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_msp_template.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_nand.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_nor.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_pccard.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_pcd.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_pcd_ex.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_pwr.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_rcc.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_rcc_ex.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_rtc.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_rtc_ex.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_sd.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_smartcard.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_spi.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_spi_ex.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_sram.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_tim.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_tim_ex.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_timebase_rtc_alarm_template.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_timebase_tim_template.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_uart.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_usart.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_wwdg.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_adc.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_crc.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_dac.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_dma.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_exti.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_fsmc.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_gpio.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_i2c.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_pwr.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_rcc.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_rtc.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_sdmmc.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_spi.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_tim.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_usart.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_usb.obj" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_utils.obj" 

C_DEPS__QUOTED += \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_adc.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_adc_ex.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_can.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_cec.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_cortex.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_crc.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_dac.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_dac_ex.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_dma.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_eth.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_flash.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_flash_ex.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_gpio.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_gpio_ex.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_hcd.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_i2c.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_i2s.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_irda.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_iwdg.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_mmc.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_msp_template.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_nand.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_nor.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_pccard.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_pcd.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_pcd_ex.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_pwr.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_rcc.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_rcc_ex.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_rtc.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_rtc_ex.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_sd.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_smartcard.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_spi.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_spi_ex.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_sram.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_tim.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_tim_ex.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_timebase_rtc_alarm_template.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_timebase_tim_template.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_uart.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_usart.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal_wwdg.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_adc.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_crc.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_dac.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_dma.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_exti.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_fsmc.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_gpio.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_i2c.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_pwr.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_rcc.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_rtc.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_sdmmc.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_spi.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_tim.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_usart.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_usb.d" \
"Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_ll_utils.d" 

C_SRCS__QUOTED += \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc_ex.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_can.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cec.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_crc.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dac.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dac_ex.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_eth.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_flash_ex.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_gpio_ex.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_hcd.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2c.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_i2s.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_irda.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_iwdg.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_mmc.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_msp_template.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_nand.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_nor.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pccard.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd_ex.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pwr.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rcc_ex.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_rtc_ex.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_sd.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_smartcard.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_spi_ex.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_sram.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_tim_ex.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_timebase_rtc_alarm_template.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_timebase_tim_template.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_uart.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_usart.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_wwdg.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_adc.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_crc.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_dac.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_dma.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_exti.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_fsmc.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_gpio.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_i2c.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_pwr.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_rcc.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_rtc.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_sdmmc.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_spi.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_tim.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usart.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c" \
"../Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_utils.c" 


